#include "header.h"

int main()
{
    // // Attach a file manager object to poem.txt
    // FileManager file_manager("poem.txt");

    // // Save the map generated by the file manager, this map contains the frequency information for the file
    // std::map<std::string, int> my_map = file_manager.generate_map();

    // std::cout << "FileManager's file_name: " << file_manager.get_file_name() << std::endl;

    // // Print the map
    // for(auto it = my_map.begin(); it != my_map.end(); it++)
    //     std::cout << "Word: " << it->first << "\tFrequency: " << it->second << std::endl;

    // // Attach a huffman code to this frequency map and retrieve the codelist
    // HuffmanCode my_huffman_code(my_map);
    // std::map<std::string, std::string> my_codelist = my_huffman_code.get_codelist();

    // // Print out the codebook
    // for(auto it = my_codelist.begin(); it != my_codelist.end(); it++)
    //     std::cout << "Plaintext: " << it->first << "\tCodeword: " << it->second << std::endl;

    Compressor compressor("poem.txt");
    
    return 0;
}